language: node_js
sudo: false
env:
- CXX=g++-4.8
services:
  - mongodb
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
node_js:
- '4.3.1'
before_script:
- sleep 15
- npm install grunt-cli -g
notifications:
  slack:
    secure: b/n0XTCyljik3qiWBzIbN8d5RfCsYmBdu5tIFtB80113DUalrl5u14T1ir+LsLYGsS3Y2qpZGPLfHghj4p80Llv3i20NBKbCFhvAIvFqWOIA3hgLQ2zJyPE22i+0cufWlBLPXwFuSiLG2qM0lFK7vk9wXwfnktrwcNhApsCq472f/B1xmQ0C841kwVxeI36K2K5CFvNV+7854+QuAgQpaoV8jShyA2XVocId8/U4YFKvUQX7/1Tk/dMkfF7GfSyYFnfyBTrw3gAb+TJre7RQHatgn5mU6zKovkWwveqVvwcJNlxCmqV6XyRTvbEOv0t56eLaoGgfD7JTuPdnvq7cEJE5Kr0HonUwzuXmLryImUQVdTi2NjRuEnx+JPi7H6j7Cr1toIP6l/rYJ74dsOjtrzZZZbzl7tsbo18hqohigqd5nO6FesOhbxf0Xj3rXSv29AHbMEySVIJZ1yw7GMUN45HefGohCjsKDgyzB9bhIkLZryw97kqwAnyhiBsR+NA6IUBig4Wa8tuGrnXRXEjkgPZfs3C/UZBVRP5d5qQ04aKG7WZOeZq6N24Sf58Whsy3d21Tt++DfK5NXpBx6d6ORRksXDgcGwjGJ0tCoeiBlM5IYONBi1UoW9xtHTT67LgS1ftp00fJuSHnK4MAnH23VuTi32H+LWXnRfZF4Cm6lf0=
